services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.lite
    container_name: cheminformatics-microservice-lite
    env_file:
      - .env
    environment:
      - HOMEPAGE_URL=https://docs.api.naturalproducts.net
      - RELEASE_VERSION=v2.6.0
      - WORKERS=2  # Make workers configurable
      - INCLUDE_OCSR=false
    ports:
      - "80:80"
    healthcheck:
      test: curl -f http://localhost:80/latest/chem/health || exit 1
      interval: 90s
      timeout: 10s
      retries: 20
      start_period: 60s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - cm_fastapi

  prometheus:
    image: prom/prometheus:latest  # Specify version for better stability
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    networks:
      - cm_fastapi

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472"  # Grafana's official user ID
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}  # Configurable password
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - cm_fastapi

volumes:
  prometheus_data:
  grafana_data:

networks:
  cm_fastapi:
    name: cm_fastapi
    driver: bridge