version: "3.8"

services:
  traefik:
    image: traefik:v3.1.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
     # - 8080:8080 # Optional: Expose Traefik dashboard on port 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: nfdi4chem/cheminformatics-microservice:v2.6.0
    environment:
      HOMEPAGE_URL:  "https://docs.api.naturalproducts.net"
      RELEASE_VERSION: v2.6.0
    pull_policy: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)" # adapt this value to your needs
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/latest/chem/health"]
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 40s

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./../prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  init_grafana:
    image: grafana/grafana:latest
    user: root
    entrypoint:
      - /bin/sh
      - -c
      - |
        chown -R 65534:65534 /var/lib/grafana
    volumes:
      - /mnt/data/grafana_data:/var/lib/grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "65534"
    ports:
      - 3000:3000
    volumes:
      - /mnt/data/grafana_data:/var/lib/grafana
    depends_on:
      - init_grafana
volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/data/prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/data/grafana_data
networks:
  default:
    name: cm_fastapi
