
# This worklflow will perform following actions when a release is published:
# - Fetch Latest release.
# - Build the latest docker image in production.
# - Push the docker image to Github Artifact Registry-Prod.
# 
# Maintainers:
#   - name: Nisha Sharma
#   - email: nisha.sharma@uni-jena.de

name : Prod Build, Test and Publish

on:
  release:
    types: [published]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: europe-west3-a
  REPOSITORY_NAME: cheminformatics-python-microservice
  APP_IMAGE: chem-py-microservice

jobs:
  setup-build-publish-prod:
    name: Build & publish to prod registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - name: Setup CLI
      uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Configure docker
      run: |-
        gcloud auth configure-docker europe-west3-docker.pkg.dev

    #Fetch latest release
    - name: Fetch latest release
      id: fetch-latest-release
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        myToken: ${{ github.token }}
        exclude_types: "draft"
        view_top: 10
    - name: "Print release name"
      run: |
        echo "tag_name: ${{ steps.fetch-latest-release.outputs.tag_name }}"

    # Build the Docker image
    - name: Build docker image
      run: |-
        docker build --build-arg RELEASE_VERSION=${{ steps.fetch-latest-release.outputs.tag_name }}  --tag "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$APP_IMAGE:latest" .
        
    # Push the Docker image to Google Container Registry
    - name: Publish image to Google Artifact Registry
      run: |-
        docker push "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$APP_IMAGE:latest"