name: Unit test and Lint check

on:  
  pull_request:
    branches:
        - development
        - main

jobs:
  test:
    uses: Steinbeck-Lab/cheminformatics-microservice/.github/workflows/test.yml@main